#!/bin/sh

# Highly experimental faetch of two useful images from the same time. In order to be
# useful as overlays the underlying map should be removed from the satellite image.

YEAR=2022
MONTH=11
DAY=14

TODAY=$YEAR$MONTH$DAY

TODAY=`date +%Y%m%d`

wget -O $HOME/weather/atl_analysis.png https://www.met.ie/images/surface-analysis/web17_atl_analysis+wbpt_${TODAY}_00.png > /dev/null 2>&1

